"""Add revoked token blocklist

Revision ID: 432747e08178
Revises: 6b567861b048
Create Date: 2026-10-07 08:04:24.726842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432747e08178'
down_revision = '6b567861b048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_token_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_token_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_token_expires_at'))

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
